(()=>{const root=document.querySelector('.ld-ecosystem');if(!root)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const ob=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){ob.disconnect();start().catch(()=>root.classList.add('unavailable'));}},{rootMargin:'700px'});ob.observe(root);
async function start(){const T=await import('./assets/three.module.js'),view=root.querySelector('.ld-eco-view'),renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));root.querySelector('.ld-eco-canvas').append(renderer.domElement);const scene=new T.Scene(),camera=new T.OrthographicCamera(-5,5,4,-4,.1,100);camera.position.set(0,3.6,10);camera.lookAt(0,0,0);const world=new T.Group();scene.add(world);const surface=new T.MeshBasicMaterial({color:0x263329,polygonOffset:true,polygonOffsetFactor:1,polygonOffsetUnits:1});const ink=new T.LineBasicMaterial({color:0xddebaf,transparent:true,opacity:.9});
function part(g,parent=world){const m=new T.Mesh(g,surface);m.add(new T.LineSegments(new T.EdgesGeometry(g),ink));parent.add(m);return m;}
function box(w,h,d,x,y,z,parent=world){const m=part(new T.BoxGeometry(w,h,d),parent);m.position.set(x,y,z);return m;}
const house=new T.Group();world.add(house);box(1.8,1.45,1.45,0,-.2,0,house);box(2.4,.1,2.05,0,-.99,0,house);box(.36,.83,.025,.3,-.5,.75,house);box(.51,.45,.026,-.46,-.12,.75,house);box(.026,.45,.54,.92,-.12,.1,house);
const shape=new T.Shape();shape.moveTo(-1.08,0);shape.lineTo(0,.85);shape.lineTo(1.08,0);shape.closePath();const roof=part(new T.ExtrudeGeometry(shape,{depth:1.7,bevelEnabled:false}),house);roof.position.set(0,.55,-.85);box(.24,.5,.28,.61,1.14,-.3,house);
function textPlane(text,w,h,parent,x,y,z){const c=document.createElement('canvas');c.width=600;c.height=360;const ctx=c.getContext('2d');ctx.fillStyle='#ddebaf';ctx.font='26px monospace';ctx.fillText(text[0],35,65);ctx.font='38px Arial';ctx.fillText(text[1],35,145);ctx.strokeStyle='#7a9269';ctx.lineWidth=2;for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(35,205+i*34);ctx.lineTo(i===2?355:555,205+i*34);ctx.stroke();}const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),transparent:true,depthWrite:false}));m.position.set(x,y,z);parent.add(m);}
const specs=[{x:-2.55,y:.75,z:-.2,t:['01 / EXISTING CRM','Property records']},{x:2.55,y:.75,z:-.2,t:['02 / PROPERTY','Shared context']},{x:-2.55,y:-.75,z:.5,t:['03 / BUYER','Needs & preferences']},{x:2.55,y:-.75,z:.5,t:['04 / NEXT STEP','Offers & follow-up']}];
const nodes=specs.map(s=>{const group=new T.Group();world.add(group);box(1.85,1.1,.09,0,0,0,group);textPlane(s.t,1.75,1.05,group,0,0,.06);group.position.set(s.x,s.y,s.z);return group;});
const links=specs.map(s=>{const g=new T.BufferGeometry().setFromPoints([new T.Vector3(0,-.8,0),new T.Vector3(s.x*.7,-.8,s.z),new T.Vector3(s.x,s.y,s.z)]);const m=new T.Line(g,new T.LineDashedMaterial({color:0xd9ee95,dashSize:.07,gapSize:.065,transparent:true,opacity:.6}));m.computeLineDistances();world.add(m);return m;});
const descriptions=['Bring the existing property record into a shared place for the next conversation.','Keep property information and the people involved around one shared point of reference.','Connect inspection interest with buyer needs, preferences and useful follow-up.','Carry the property and relationship context into offer review and the next conversation.'];
let p=0,frame=0,visible=true;const clamp=n=>Math.max(0,Math.min(1,n));const slider=root.querySelector('input'),steps=[...root.querySelectorAll('li')];
function draw(){frame=0;if(!visible)return;const phase=Math.min(3,Math.floor(p*4));world.rotation.y=-.22+p*.42;house.rotation.y=-.3+p*.4;house.position.y=Math.sin(p*Math.PI)*.12;nodes.forEach((n,i)=>{const amount=clamp(p*4-i+.55);n.scale.setScalar(.68+amount*.32);n.position.y=specs[i].y-(1-amount)*.3;n.visible=amount>0;links[i].visible=amount>0;});root.querySelector('.ld-eco-description').textContent=descriptions[phase];steps.forEach((s,i)=>s.classList.toggle('active',i===phase));root.style.setProperty('--progress',p);slider.value=Math.round(p*100);renderer.render(scene,camera);root.dataset.phase=phase;root.dataset.progress=p.toFixed(3);}
function queue(){if(!frame)frame=requestAnimationFrame(draw);}
function resize(){const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h);const span=Math.max(6.1,8.5*h/w);camera.left=-span*w/h/2;camera.right=span*w/h/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();queue();}
function scroll(){if(reduced.matches)return;const b=root.getBoundingClientRect();p=clamp((60-b.top)/(b.height-innerHeight+60));queue();}
function motion(){root.classList.toggle('animated',!reduced.matches);p=reduced.matches?1:0;resize();if(!reduced.matches)scroll();}
slider.addEventListener('input',()=>{p=Number(slider.value)/100;queue();});addEventListener('scroll',scroll,{passive:true});new ResizeObserver(resize).observe(view);reduced.addEventListener('change',motion);new IntersectionObserver(es=>{visible=es[0].isIntersecting;if(visible)queue();}).observe(root);root.classList.add('ready');motion();
}})();
